function [Optimized_DesignVars, Info] = OptimizationCPGPernaDireitaQ1(DesignVars)
%RESPONSEOPTIMIZATIONCPGPERNADIREITA
%
% Solve a design optimization problem for the CPGPernaDireita model.
%
% The function returns optimized parameter values, Optimized_DesignVars,
% and optimization termination information, Info.
%
% The input argument, DesignVars, defines the model parameters to optimize,
% if omitted the parameters specified in the function body are optimized.
%
% Modify the function to include or exclude new design requirements, or
% to change the optimization options.
%
% Auto-generated by SDOTOOL on 04-Apr-2022 08:43:40.
%

%% Open the model.
open_system('CPGPernaDireita')

%% Specify Design Variables
%
% Specify model parameters as design variables to optimize.
if nargin < 1 || isempty(DesignVars)
    DesignVars = sdo.getParameterFromModel('CPGPernaDireita',{'S1','b1','tr1','tr2','ta2','w12','w13','w21','w24'});
    DesignVars(1).Value = 6.946714221790271;
    DesignVars(1).Minimum = 0;
    DesignVars(1).Scale = 1;
    DesignVars(2).Value = 0.1424555881472682;
    DesignVars(2).Minimum = 0;
    DesignVars(2).Scale = 8192;
    DesignVars(3).Value = 0.0311070924161197;
    DesignVars(3).Minimum = 0;
    DesignVars(4).Value = 0.003095919542894938;
    DesignVars(4).Minimum = 0;
    DesignVars(5).Value = 1.14025714534038e-13;
    DesignVars(5).Minimum = 0;
    DesignVars(5).Scale = 1.13686837721616e-13;
    DesignVars(6).Value = -4.129108228957395;
    DesignVars(6).Maximum = 0;
    DesignVars(6).Scale = 8;
    DesignVars(7).Value = -1.904445614222063;
    DesignVars(7).Maximum = 0;
    DesignVars(7).Scale = 4;
    DesignVars(8).Value = -0.9145038960139219;
    DesignVars(8).Maximum = 0;
    DesignVars(9).Value = 1.029938981175686;
end

%% Specify Design Requirements
%
% Specify design requirements to satisfy during optimization.
Requirements = struct;
Requirements.SignalTracking = sdo.requirements.SignalTracking(...
    'Method', 'SSE', ...
    'ReferenceSignal', getData('SignalTracking_ReferenceSignal'), ...
    'RobustCost', 'on', ...
    'Weights', getData('SignalTracking_Weights'));

%% Simulation Definition
%
% Specify model signals to log during model simulation.
Simulator = sdo.SimulationTest('CPGPernaDireita');

oscQD1_Info = Simulink.SimulationData.SignalLoggingInfo;
oscQD1_Info.BlockPath = 'CPGPernaDireita/Add1';
oscQD1_Info.LoggingInfo.LoggingName = 'oscQD1';
oscQD1_Info.LoggingInfo.NameMode = 1;

Simulator.LoggingInfo.Signals = oscQD1_Info;

%% Create Optimization Objective Function
%
% Create a function that is called at each optimization iteration
% to evaluate the design requirements.
%
% Use an anonymous function with one argument that calls CPGPernaDireita_optFcn.
optimfcn = @(P) CPGPernaDireita_optFcn(P,Simulator,Requirements);

%% Optimization Options
%
% Specify optimization options.
Options = sdo.OptimizeOptions;
Options.MethodOptions.ConstraintTolerance = 0.0001;
Options.MethodOptions.FunctionTolerance = 0.0001;
Options.MethodOptions.MaxIterations = 250;
Options.MethodOptions.OptimalityTolerance = 0.0001;
Options.MethodOptions.StepTolerance = 0.0001;
Options.OptimizedModel = Simulator;
Options.StopIfFeasible = 'off';

%% Optimize the Design
%
% Call sdo.optimize with the objective function handle, parameters to
% optimize, and options.
[Optimized_DesignVars,Info] = sdo.optimize(optimfcn,DesignVars,Options);

%% Update Model
%
% Update the model with the optimized parameter values.
sdo.setValueInModel('CPGPernaDireita',Optimized_DesignVars);
end

function Vals = CPGPernaDireita_optFcn(P,Simulator,Requirements)
%CPGPERNADIREITA_OPTFCN
%
% Function called at each iteration of the optimization problem.
%
% The function is called with a set of parameter values, P, and returns
% the objective value and constraint violations, Vals, to the optimization
% solver.
%
% See the sdoExampleCostFunction function and sdo.optimize for a more
% detailed description of the function signature.
%

%% Model Evaluation

% Simulate the model.
Simulator.Parameters = P;
Simulator = sim(Simulator);

% Retrieve logged signal data.
SimLog = find(Simulator.LoggedData,get_param('CPGPernaDireita','SignalLoggingName'));
oscQD1_Log = find(SimLog,'oscQD1');

% Evaluate the design requirements.
F_SignalTracking = evalRequirement(Requirements.SignalTracking,oscQD1_Log.Values);

%% Return Values.
%
% Collect the evaluated design requirement values in a structure to
% return to the optimization solver.
Vals.F = F_SignalTracking;
end

function Data = getData(DataID)
%GETDATA
%
% Helper function to store data used by responseOptimization_CPGPernaDireita.
%
% The input, DataID, specifies the name of the data to retrieve. The output,
% Data, contains the requested data.
%

switch DataID
    case 'SignalTracking_ReferenceSignal'
        t = [0; 0.0114737630037639; 0.0229475260075279; 0.0344212890112918; 0.0458950520150558;  ...
            0.0573688150188197; 0.0688425780225837; 0.0803163410263476; 0.09179010403011161;  ...
            0.103263867033876; 0.114737630037639; 0.126211393041403; 0.137685156045167;  ...
            0.149158919048931; 0.160632682052695; 0.172106445056459; 0.183580208060223;  ...
            0.195053971063987; 0.206527734067751; 0.218001497071515; 0.229475260075279;  ...
            0.240949023079043; 0.252422786082807; 0.263896549086571; 0.275370312090335;  ...
            0.286844075094099; 0.298317838097863; 0.309791601101627; 0.32126536410539;  ...
            0.332739127109154; 0.344212890112918; 0.355686653116682; 0.367160416120446;  ...
            0.37863417912421; 0.390107942127974; 0.401581705131738; 0.413055468135502;  ...
            0.424529231139266; 0.43600299414303; 0.447476757146794; 0.458950520150558;  ...
            0.470424283154322; 0.481898046158086; 0.49337180916185; 0.504845572165614;  ...
            0.516319335169378; 0.527793098173142; 0.539266861176906; 0.550740624180669;  ...
            0.562214387184433; 0.573688150188197; 0.585161913191961; 0.596635676195725;  ...
            0.608109439199489; 0.619583202203253; 0.631056965207017; 0.6425307282107811;  ...
            0.654004491214545; 0.665478254218309; 0.676952017222073; 0.688425780225837;  ...
            0.699899543229601; 0.711373306233365; 0.722847069237129; 0.734320832240893;  ...
            0.745794595244657; 0.75726835824842; 0.768742121252184; 0.780215884255948;  ...
            0.791689647259712; 0.803163410263476; 0.8146371732672399; 0.826110936271004;  ...
            0.837584699274768; 0.849058462278532; 0.860532225282296; 0.87200598828606;  ...
            0.883479751289824; 0.894953514293588; 0.906427277297352; 0.917901040301116;  ...
            0.92937480330488; 0.940848566308644; 0.952322329312408; 0.963796092316172;  ...
            0.975269855319936; 0.9867436183236989; 0.998217381327463; 1.00969114433123;  ...
            1.02116490733499; 1.03263867033876; 1.04411243334252; 1.05558619634628;  ...
            1.06705995935005; 1.07853372235381; 1.09000748535758; 1.10148124836134;  ...
            1.1129550113651; 1.12442877436887; 1.13590253737263];
        y = [25.6130808597337; 25.70298471417129; 25.61233133725937; 25.35043342410668;  ...
            24.98909651708693; 24.55916810219588; 24.05322896545191; 23.45341821634984;  ...
            22.752163886112; 21.95873531631852; 21.09522638965339; 20.18821066579286;  ...
            19.26110872373465; 18.32987625249588; 17.40238256178802; 16.48041688855304;  ...
            15.56273185604967; 14.64771939576834; 13.7349050280507; 12.82513042679487;  ...
            11.91983127273239; 11.02007325080447; 10.12596074408151; 9.236751122362886;  ...
            8.351623800086406; 7.470717559867508; 6.595888138363579; 5.730716153310984;  ...
            4.879594331804526; 4.046136772498741; 3.231513132340766; 2.433442123538724;  ...
            1.646379444020282; 0.8629484102223755; 0.07609304485949231; -0.7189232342056764;  ...
            -1.523469245606732; -2.335724221012517; -3.151670770974499; -3.9660491021327;  ...
            -4.77252804949795; -5.562979179435033; -6.326502278387623; -7.049217755773641;  ...
            -7.715502812024669; -8.310450273295093; -8.822422334143699; -9.244268863758311;  ...
            -9.572344827618254; -9.803608490985312; -9.932141506540358; -9.946774568293851;  ...
            -9.830941491884374; -9.564783829986254; -9.128546700569549; -8.505968060273736;  ...
            -7.686742113786968; -6.667861900190459; -5.454194637112535; -4.058704614973899;  ...
            -2.502390780826897; -0.8136128997759879; 0.9735983635559586; 2.822315037981047;  ...
            4.696095964334635; 6.562123594066021; 8.39326482785647; 10.16866511973099;  ...
            11.87308546491995; 13.49563532802758; 15.02863758471284; 16.46709148579338;  ...
            17.8087572365931; 19.05450440792214; 20.20841138519658; 21.27721215907182;  ...
            22.26898206965719; 23.19129722052137; 24.04935611341405; 24.84462569836413;  ...
            25.57444373891251; 26.23271860994372; 26.81151108789985; 27.30297969529389;  ...
            27.70103361541776; 28.00213732319301; 28.20505432850436; 28.30982573418841;  ...
            28.31679002256706; 28.22673621652179; 28.04309723581621; 27.77624662574566;  ...
            27.44844567437715; 27.09611437191354; 26.76471665983021; 26.49229484799871;  ...
            26.28329964146322; 26.08906041331417; 25.84116983171175; 25.63780646561824];
        Data = timeseries(y,t);
    case 'SignalTracking_Weights'
        Data = [1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1;  ...
            1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1;  ...
            1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1;  ...
            1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1;  ...
            1; 1; 1; 1];
end
end
